# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Debug
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build Release
      run: dotnet build --no-restore -c Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PngParser-artifact-linux-main.zip
        path: |
          bin/Release/net9.0/PngParser
          bin/Release/net9.0/PngParser.dll
          bin/Release/net9.0/PngParser.runtimeconfig.json
    - name: Attestation
      uses: actions/attest-build-provenance@v3
      with:
        subject-name: PngParser-artifact-linux-main.zip
        subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}

  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Debug
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build Release
      run: dotnet build --no-restore -c Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PngParser-artifact-windows-main.zip
        path: |
          bin/Release/net9.0/PngParser.exe
          bin/Release/net9.0/PngParser.dll
          bin/Release/net9.0/PngParser.runtimeconfig.json
    - name: Attestation
      uses: actions/attest-build-provenance@v3
      with:
        subject-name: PngParser-artifact-windows-main.zip
        subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
